### ISSUE TITLE
Symfony Bundle broken due to invalid service definition

### ISSUE THREAD

**Issue by mbadolato** [qandidate-labs/broadway#105]
When the Symfony Bundle is enabled, Symfony attempts to build the service container, which includes loading the [services.xml](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Bundle/BroadwayBundle/Resources/config/services.xml) file.

That `services.xml` file contains a definition for `broadway.auditing.command_logger`:

``` xml
<service id="broadway.auditing.command_logger" class="Broadway\Auditing\CommandLogger">
    <argument><!-- logger --></argument>
    <argument type="service" id="broadway.auditing.serializer" />
    <tag name="broadway.event_listener" event="broadway.command_handling.command_success" method="onCommandHandlingSuccess" />
    <tag name="broadway.event_listener" event="broadway.command_handling.command_failure" method="onCommandHandlingFailure" />
</service>
```

However, since [CommandLogger.php](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Auditing/CommandLogger.php) requires an object that implements `Psr\Log\LoggerInterface` to be passed in as the first argument:

``` php
public function __construct(LoggerInterface $logger, CommandSerializerInterface $commandSerializer)
```

we get an error because the service definition has a string (the `<!-- logger -->` placeholder) defined.

The configuration 

``` yml
broadway:
    command_handling:
        logging: false
```

has no effect on this since this is simple Symfony service container building and not conditional based on the configs.

That placeholder string in the service definition needs to be replaced with an actual logger implementation.

A yml configuration option to define a PSR logger should be defined and the service definition could use that object definition.  Ideally this config option could take a class name or a service definition

``` yml
broadway:
    command_handling:
        logging: true
            logger: Acme\Path\To\MyPsrLogger
```

or

``` yml
broadway:
    command_handling:
        logging: true
            logger: [@monolog.logger]
```

This doesn't solve the issue of a logger not being defined if logging is `false` so either
1. the service definition should only be dynamically created if logging is `true` or 
2. (optimally) a default Broadway PSR Logger object needs to be defined and used if logging is `false` and/or no logger config is specified (`logger: ~`)
