### ISSUE TITLE
Metadata enrichment does not have any effect

### ISSUE THREAD

**Issue by aleixverges** [qandidate-labs/broadway#249]
Hi,

I've my metadata enricher registered as follows using symfony:

```
acme.metadata_enricher.author:
    class: Acme\CoreBundle\Infrastructure\Messaging\AuthorMetadataEnricher  
        arguments: [@security.token_storage]  
        tags:  
            - { name: broadway.metadata_enricher }
```  

The Metadata Enricher is coded as follows:

```
<?php

namespace Acme\CoreBundle\Infrastructure\Messaging;

use Broadway\Domain\Metadata;
use Broadway\EventSourcing\MetadataEnrichment\MetadataEnricherInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class AuthorMetadataEnricher implements MetadataEnricherInterface
{
    /**
     * @var TokenStorageInterface
     */
    private $tokenStorage;

    /**
     * @param TokenStorageInterface $tokenStorage
     */
    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    /**
     * @param Metadata $existingMetadata
     * @return Metadata
     */
    public function enrich(Metadata $existingMetadata)
    {
        $username = $this->tokenStorage->getToken() ? $this->tokenStorage->getToken()->getUsername() : 'System';
        $metadata = new Metadata(['author' => $username]);

        return $existingMetadata->merge($metadata);
    }
}
```  

And my Domain Events are applied using the "apply" method defined in EventSourcedAggregateRoot class.

   The problem is that no metadata is registered in my events and it seems that the enrichment does not take part during the event flow. Is there anything I'm missing?

Thanks
